// Autogenerated from Pigeon (v0.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class MessageReply;
@class MessageRequest;

@interface MessageReply : NSObject
@property(nonatomic, copy, nullable) NSString * query;
@end

@interface MessageRequest : NSObject
@property(nonatomic, copy, nullable) NSString * result;
@end

@protocol Api
-(nullable MessageReply *)sendMessage:(MessageRequest*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void ApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<Api> _Nullable api);

NS_ASSUME_NONNULL_END
