// Autogenerated from Pigeon (v0.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import
import 'dart:async';
import 'package:flutter/services.dart';

class MessageReply {
  String query;
  // ignore: unused_element
  Map<dynamic, dynamic> _toMap() {
    final Map<dynamic, dynamic> pigeonMap = <dynamic, dynamic>{};
    pigeonMap['query'] = query;
    return pigeonMap;
  }
  // ignore: unused_element
  static MessageReply _fromMap(Map<dynamic, dynamic> pigeonMap) {
    final MessageReply result = MessageReply();
    result.query = pigeonMap['query'];
    return result;
  }
}

class MessageRequest {
  String result;
  // ignore: unused_element
  Map<dynamic, dynamic> _toMap() {
    final Map<dynamic, dynamic> pigeonMap = <dynamic, dynamic>{};
    pigeonMap['result'] = result;
    return pigeonMap;
  }
  // ignore: unused_element
  static MessageRequest _fromMap(Map<dynamic, dynamic> pigeonMap) {
    final MessageRequest result = MessageRequest();
    result.result = pigeonMap['result'];
    return result;
  }
}

class Api {
  Future<MessageReply> sendMessage(MessageRequest arg) async {
    final Map<dynamic, dynamic> requestMap = arg._toMap();
    const BasicMessageChannel<dynamic> channel =
        BasicMessageChannel<dynamic>('dev.flutter.pigeon.Api.sendMessage', StandardMessageCodec());
    
    final Map<dynamic, dynamic> replyMap = await channel.send(requestMap);
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
        details: null);
    } else if (replyMap['error'] != null) {
      final Map<dynamic, dynamic> error = replyMap['error'];
      throw PlatformException(
          code: error['code'],
          message: error['message'],
          details: error['details']);
    } else {
      return MessageReply._fromMap(replyMap['result']);
    }
    
  }
}

